

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_cafe
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build: ./Backend
    container_name: node_backend
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: employee_cafe
      PORT: 3000
      FRONTENDURL: http://localhost:8080
    
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "npm run seed && node app.js"]

    networks:
      - backend-network

  frontend:
    build: ./Frontend
    container_name: react_frontend
    ports:
      - "8080:8080"
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
